### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by RandomAltThing** [jv110/PocketIndustrialization#2]
Can you give a really quick tutorial on adding a block? Maybe a few github costs of the needed files or just reply to this and put it inside a <pre> </pre>?

**Comment by RandomAltThing** [comment]
Costs means gists (gist.github.com)

**Comment by RandomAltThing** [comment]
It autocorrected

**Comment by jv110** [comment]
http://nativemcpe.blogspot.com.br/2015/05/native-modding-3-our-own-block.html

**Comment by RandomAltThing** [comment]
What this guy said:
Um comentário:

The Jay27 de maio de 2015 16:22
I DONT UNDERSTAND

Responder

**Comment by RandomAltThing** [comment]
I'm trying to add proper name to the tank but I get a **so and so is not declared** error.
   MSHookFunction((void*)&I18n::get, (void*)&I18n_get_hook, (void**)&I18n_get_real);

**Comment by RandomAltThing** [comment]
Ignore the above ^^
