### ISSUE TITLE
Creative Inv. Crash / Usless Items/blocks

### ISSUE THREAD

**Issue by CrazyWolf23** [jv110/PocketIndustrialization#9]
When you load items to be in the creative inv, it crashes, i guess we should refactor the items. And why is there an isolated pipe? But what my point is, please test code before pushing.

**Comment by jv110** [comment]
Isolated Cables are to prevent electric shocks (coming later when I figure out how to add), and I do test it. I also know about the Creative item crash, that's why all them are commited out.

**Comment by CrazyWolf23** [comment]
When i said "please test the code", i was kinda talking to @RandomAltThing ,  and thank you for telling me what isolated cable was
